FROM ghcr.io/gravity-ui/node-nginx:ubuntu20-nodejs18-slim

# deps installation
RUN apt-get update && \
    apt-get -y install nano vim curl git telnet bzip2 iproute2 wget

# cleanup tmp and defaults
RUN rm -rf /var/lib/apt/lists/*
